### ISSUE TITLE
fb.py fail 

### ISSUE THREAD

**Issue by gearcapitan** [misterch0c/shadowbroker#10]
C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows>fb.py

--[ Version 3.5.1

[*] Loading Plugins
===============================================================
=
= Encountered an unhandled error.  Please provide the following
= information to the developer
=
===============================================================
Traceback (most recent call last):
  File "C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows\f
uzzbunch\exception.py", line 66, in wrap
    ret = fn(*args, **kwargs)
  File "C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows\f
b.py", line 83, in setup_and_run
    load_plugins(fb)
  File "C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows\f
b.py", line 72, in load_plugins
    addplugins(fb, "ListeningPost", LP_DIR,      EDFPlugin)
  File "C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows\f
uzzbunch\pluginfinder.py", line 78, in addplugins
    plugins = getpluginlist(location, bin)
  File "C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows\f
uzzbunch\pluginfinder.py", line 36, in getpluginlist
    fblist     = getextensionfiles(location, FB_CONFIG_EXT)         # get list o
f .fb files
  File "C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows\f
uzzbunch\pluginfinder.py", line 21, in getextensionfiles
    for file in os.listdir(location)
WindowsError: [Error 3] El sistema no puede encontrar la ruta especificada: 'C:\
\Users\\gearc\\Desktop\\shadowbroker-master\\shadowbroker-master\\windows\\liste
ningposts/*.*'

C:\Users\gearc\Desktop\shadowbroker-master\shadowbroker-master\windows>

**Comment by xNymia** [comment]
This isn't a bug, you are just missing the listeningposts directory.

**Comment by gearcapitan** [comment]
who to fix?

**Comment by gearcapitan** [comment]
![windows xp professional-2017-04-18-14-03-09](https://cloud.githubusercontent.com/assets/13740942/25148229/c74cab9e-243f-11e7-8c7d-ff0ddfba3e15.png)

**Comment by xNymia** [comment]
Show me the full directory listing for \EQGRP_L_I_T\windows\

**Comment by gearcapitan** [comment]
![windows xp professional-2017-04-18-14-06-07](https://cloud.githubusercontent.com/assets/13740942/25148334/2fb694f6-2440-11e7-874e-9d381174cad5.png)

**Comment by xNymia** [comment]
Create the folder:
\EQGRP_L_I_T\windows\listeningposts\

It should then work.

**Comment by gearcapitan** [comment]
hahahahaha 
![windows xp professional-2017-04-18-14-08-36](https://cloud.githubusercontent.com/assets/13740942/25148438/891c36fe-2440-11e7-8fc0-277af86268f9.png)
Apologize for my awkwardness

**Comment by xNymia** [comment]
Thanks, please close the issue. :)

**Comment by omaress** [comment]
Please help me not work

**Comment by omaress** [comment]
![image](https://cloud.githubusercontent.com/assets/28624550/25947350/09a45f6e-3647-11e7-9ac3-15b773df25fc.png)
please help me

**Comment by xNymia** [comment]
You should read the documentation on this if you wish to use it.

**Comment by d78ui98** [comment]
hey @omaress  open the fb.py file in with sublime text editor and comment out line 26 and 72. then try running it. Let me know if it dosn't work
