### ISSUE TITLE
DanderSpritz Error Launch /!\

### ISSUE THREAD

**Issue by legendary77** [misterch0c/shadowbroker#14]
Hi boss

I have an error at the launch of "Réprimander" and I would like to know how to solve the problem

I have installed: python 2.6 pywin32.212 and java 8
thank you

**Fb.py starts correctly**

# **error :** 

http://image.prntscr.com/image/5b12c2c960d4428a9c38fe0be9138f09.png

`Traceback (most recent call last):
  File "D:\Hidden\windows\Resources\Python\Core\Lib\site.py", line 548, in <module>
    main()
  File "D:\Hidden\windows\Resources\Python\Core\Lib\site.py", line 538, in main
    aliasmbcs()
  File "D:\Hidden\windows\Resources\Python\Core\Lib\site.py", line 481, in aliasmbcs
    codecs.lookup(enc)
  File "D:\Hidden\windows\Resources\Python\Core\Lib\encodings\__init__.py", line 83, in search_function
    mod = __import__('encodings.' + modname, fromlist=_import_tail, level=0)
  File "D:\Hidden\windows\Resources\Python\Core\Lib\encodings\cp1252.py", line 44
SyntaxError: Non-ASCII character '\xe2' in file D:\Hidden\windows\Resources\Python\Core\Lib\encodings\cp1252.py on line 44, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details
`

**Comment by xNymia** [comment]
Can you describe your python environment for us: Python Version, Pywin32 version and screenshot the windows dir.

**Comment by legendary77** [comment]
http://image.prntscr.com/image/869032837bb04580a8e19346b8c9568e.png

http://image.prntscr.com/image/8d335882cb244b7cbe372976f51e7312.png

http://image.prntscr.com/image/3c649cdf42284447889266075dd79b20.png

http://image.prntscr.com/image/07adfb0eed5848f8a8904d41165f2b02.png

**Comment by ipushino** [comment]
i have same problem please help 
what is the correct java version must use

**Comment by legendary77** [comment]
Install java 6u45 bro !

**Comment by ipushino** [comment]
thanks for java
i still have the same error ( python)  what to do to bypass this issues

**Comment by sabair** [comment]
Still have the same error, I'm running python 2.6 
![mister](https://cloud.githubusercontent.com/assets/28267853/25660664/2bf38420-3005-11e7-9529-4d7eb8735c1f.jpg)

**Comment by alaponme** [comment]
Same here
