### ISSUE TITLE
Error starting DanderSpritz

### ISSUE THREAD

**Issue by ipushino** [misterch0c/shadowbroker#16]
![image](https://cloud.githubusercontent.com/assets/11677068/25307673/6380a504-2794-11e7-9026-d337ec84af07.png)

raceback (most recent call last):
  File "C:\shadowbroker\windows\Resources\Python\Core\Lib\site.py", line 548, in <module>
    main()
  File "C:\shadowbroker\windows\Resources\Python\Core\Lib\site.py", line 538, in main
    aliasmbcs()
  File "C:\shadowbroker\windows\Resources\Python\Core\Lib\site.py", line 481, in aliasmbcs
    codecs.lookup(enc)
  File "C:\shadowbroker\windows\Resources\Python\Core\Lib\encodings\__init__.py", line 83, in search_function
    mod = __import__('encodings.' + modname, fromlist=_import_tail, level=0)
  File "C:\shadowbroker\windows\Resources\Python\Core\Lib\encodings\cp1252.py", line 45
SyntaxError: Non-ASCII character '\xe2' in file C:\shadowbroker\windows\Resources\Python\Core\Lib\encodings\cp1252.py on line 45, but no encoding declared; see http://www.python.org/peps/pep-0263.html for details

**Comment by Atavic** [comment]
You are using a recent version of python. https://github.com/misterch0c/shadowbroker/issues/17#issuecomment-297266276

Downgrade IF you really want to try.

**Comment by sabair** [comment]
I'm using python 2.6 but I still get the same error! any help please?

**Comment by misterch0c** [comment]
You're executing the wrong file? Run ´configure_lp.py´

**Comment by sabair** [comment]
![mister](https://cloud.githubusercontent.com/assets/28267853/25662665/38cd1848-300d-11e7-85cf-c663d414e40d.jpg)

**Comment by d78ui98** [comment]
@sabair did you set the correct path? install jdk and start with `java -jar Start.jar` when in the correct directory

**Comment by kongjiexi** [comment]
Did you ever figure this error out? I'm just starting with it and i'd appreciate any advice.
