### ISSUE TITLE
Error running fb.py

### ISSUE THREAD

**Issue by Febin5172** [misterch0c/shadowbroker#27]
![screenshot 2](https://cloud.githubusercontent.com/assets/22743558/26092100/b4ff1870-3a2c-11e7-8ca4-978e64a19af9.jpg)
Not able to run fb.py. I have installed python latest version 2.7 and pywin32 v 12.

**Comment by Beyarz** [comment]
Try this: pip install pypiwin32

**Comment by williamros** [comment]
I think you need Python 2.6

**Comment by HerendraTJ** [comment]
go to python26\Scripts
then execute : py pywin32_postinstall.py -install

The problem is failing to post install correctly.
