### ISSUE TITLE
windowserror ERROR 126

### ISSUE THREAD

**Issue by fsebasorozco** [misterch0c/shadowbroker#30]
![image](https://cloud.githubusercontent.com/assets/25666698/26691383/84eb5ae8-46c2-11e7-9a5c-8590f369a4e3.png)
I already nistall both python2.6and pywin32 as admin, but I can't execute it

**Comment by Atavic** [comment]
Can't find the DLL module.
Related: https://github.com/jjguy/heatmap/issues/9

**Comment by HerendraTJ** [comment]
Try installing with the 32bit version. Maybe it will work

**Comment by fsebasorozco** [comment]
I did install 32bit version, y ran it on a virtual machine and works

**Comment by HerendraTJ** [comment]
Ok , closed this issue

**Comment by HerendraTJ** [comment]
Why this issue not closed??
