### ISSUE TITLE
Error Danderspirtz : Prematurely started

### ISSUE THREAD

**Issue by HerendraTJ** [misterch0c/shadowbroker#31]
Command 
D:\shadowbroker\windows\Resources\Dsz\....\....\Bin\i386-winnt-vc9\release\Dszlp.exe was prematurely terminated

Anyone help with that error??

![image](https://cloud.githubusercontent.com/assets/24410807/26770403/cb933cd8-49e0-11e7-9265-f13c3698a61b.png)

**Comment by kongjiexi** [comment]
Haven't figured this one out yet either. But I just started messing with it yesterday. Any luck so far?

**Comment by HerendraTJ** [comment]
I Think i should close this issue due it won't work anymore. People maybe more comfortable use metasploit than this.

**Comment by 5p3c7r3** [comment]
Actually this repo has a corrupted version of danderspritz as this one is working : https://github.com/fuzzbunch/fuzzbunch
